# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mturk_id', models.CharField(max_length=15)),
                ('val1', models.CharField(max_length=20)),
                ('val2', models.CharField(max_length=20)),
                ('q1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
