# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mturk_id', models.CharField(max_length=15)),
                ('val1', models.CharField(max_length=20)),
                ('val2', models.CharField(max_length=50)),
            ],
        ),
    ]
