# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_intention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='mturk_id',
        ),
        migrations.AddField(
            model_name='data',
            name='fig_id',
            field=models.IntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='val1',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='data',
            name='val2',
            field=models.IntegerField(max_length=20),
        ),
    ]
