# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171220_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('full', models.BooleanField()),
                ('wid1', models.CharField(max_length=15)),
                ('wid2', models.CharField(max_length=15)),
                ('wid3', models.CharField(max_length=15)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='FeedbackModel',
        ),
        migrations.DeleteModel(
            name='Intention',
        ),
    ]
