# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171221_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_id', models.IntegerField()),
                ('mturk_id', models.CharField(max_length=15)),
                ('positivity1', models.CharField(max_length=10)),
                ('excitement1', models.CharField(max_length=10)),
                ('positivity2', models.CharField(max_length=10)),
                ('excitement2', models.CharField(max_length=10)),
                ('bodyexpression1', models.CharField(max_length=50)),
                ('bodyexpression2', models.CharField(max_length=50)),
                ('_len', models.TextField()),
                ('elapsedtime', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RenameField(
            model_name='assign',
            old_name='vid',
            new_name='vname',
        ),
    ]
