# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionhit',
            name='elapsedtime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emotionhit',
            name='excitement1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emotionhit',
            name='excitement2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emotionhit',
            name='positivity1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emotionhit',
            name='positivity2',
            field=models.IntegerField(),
        ),
    ]
