# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20171221_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotionhit',
            old_name='_len',
            new_name='length',
        ),
    ]
