# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20171221_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='start',
            field=models.IntegerField(),
        ),
    ]
