# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_assign_emotionhit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('segment_id', models.IntegerField()),
                ('mturk_id', models.CharField(max_length=15)),
                ('timestamps', models.CharField(max_length=20)),
                ('comments', models.TextField()),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='emotionhit',
            old_name='assign_id',
            new_name='segment_id',
        ),
    ]
