# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20171228_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fig_id', models.IntegerField(default=0, max_length=15)),
                ('val1', models.IntegerField(max_length=20)),
                ('val2', models.IntegerField(max_length=20)),
                ('q1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Intention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mturk_id', models.CharField(max_length=15)),
                ('val1', models.CharField(max_length=20)),
                ('val2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aId', models.CharField(max_length=20)),
                ('wId', models.CharField(max_length=20)),
                ('timeUsed', models.FloatField()),
                ('start_time', models.CharField(max_length=40)),
                ('finish_time', models.CharField(max_length=40)),
                ('label_time', models.IntegerField()),
                ('arousal', models.FloatField()),
                ('valence', models.FloatField()),
            ],
        ),
    ]
