# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_feedback_selflabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=50)),
                ('sequnce_num', models.IntegerField(default=-1)),
                ('video_length', models.FloatField(default=0)),
                ('start_time_in_whole', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default='', max_length=50)),
                ('video_condition', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='EmotionHit',
        ),
        migrations.DeleteModel(
            name='Experiment3',
        ),
        migrations.DeleteModel(
            name='FeedbackModel',
        ),
        migrations.DeleteModel(
            name='Intention',
        ),
        migrations.RemoveField(
            model_name='labels',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='labels',
            name='label_time',
        ),
        migrations.RemoveField(
            model_name='labels',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='labels',
            name='timeUsed',
        ),
        migrations.AddField(
            model_name='labels',
            name='label_time_in_video',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='labels',
            name='label_time_in_whole',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='segment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Video'),
        ),
        migrations.AddField(
            model_name='labels',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Segment'),
        ),
        migrations.AddField(
            model_name='labels',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Video'),
        ),
    ]
