# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20180112_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='sequnce_num',
            new_name='sequence_num',
        ),
    ]
