# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20180112_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskmarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aId', models.CharField(max_length=20)),
                ('wId', models.CharField(max_length=20)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Segment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Video')),
            ],
        ),
    ]
