# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 06:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_taskmarker_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmarker',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskmarker',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 6, 28, 30, 928854)),
        ),
    ]
