# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20180112_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmarker',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 8, 29, 7, 521453)),
        ),
    ]
