# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20180112_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmarker',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Segment'),
        ),
        migrations.AlterField(
            model_name='taskmarker',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 13, 50, 54, 207331)),
        ),
        migrations.AlterField(
            model_name='taskmarker',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Video'),
        ),
    ]
